### ISSUE TITLE
`Result::unwrap() on an 'Err' value: OddLength'` Error when running `create-evm-verifier`

### ISSUE THREAD

**Issue by JSeam2** [zkonduit/ezkl#128]
Here are the steps I followed.

1. I created a gen.py to generate a onnx file with pyezkl and generated the `inputs.json` and `network.onnx` file accordingly

```python
import io
import numpy as np
from torch import nn
import torch.onnx
import torch.nn as nn
import torch.nn.init as init
import json
from ezkl import export

class Model(nn.Module):
    def __init__(self, inplace=False):
        super(Model, self).__init__()

        self.aff1 = nn.Linear(3,1)
        self.relu = nn.ReLU()
        self._initialize_weights()

    def forward(self, x):
        x =  self.aff1(x)
        x =  self.relu(x)
        return (x)


    def _initialize_weights(self):
        init.orthogonal_(self.aff1.weight)

circuit = Model()
export(circuit, input_shape = [3])

```

2. Next I generated the kzg.params as follows
```shell
ezkl -K=19 gen-srs --pfsys=kzg --params-path=kzg.params
```

3. After which I ran the following to generate the proof
```shell
ezkl --bits=16 -K=17 --public-inputs --public-outputs prove \
-D ./input.json \
-M ./network.onnx \
--proof-path proof.pf \
--vk-path proof.vk \
--params-path=kzg.params \
--transcript=evm
```

4. Then I ran the following to generate the evm verifier
```shell
ezkl -K=17 --bits=16 create-evm-verifier \
-D ./input.json \
-M ./network.onnx \
--pfsys=kzg \
--deployment-code-path proof.code \
--params-path=kzg.params \
--vk-path proof.vk \
--sol-code-path verify.sol
```

This led to the following error
```
[*] 
 |          ███████╗███████╗██╗  ██╗██╗
 |          ██╔════╝╚══███╔╝██║ ██╔╝██║
 |          █████╗    ███╔╝ █████╔╝ ██║
 |          ██╔══╝   ███╔╝  ██╔═██╗ ██║
 |          ███████╗███████╗██║  ██╗███████╗
 |          ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝
 |  
 |          -----------------------------------------------------------
 |          Easy Zero Knowledge for Liberty.
 |          -----------------------------------------------------------
 |          
[*] {"command":{"CreateEVMVerifier":{"data":"./input.json","model":"./network.onnx","params_path":"kzg.params","vk_path":"proof.vk","deployment_code_path":"proof.code","sol_code_path":"verify.sol","pfsys":"KZG"}},"args":{"tolerance":0,"scale":7,"bits":16,"logrows":17,"public_inputs":false,"public_outputs":true,"public_params":false,"max_rotations":512}}
[*] loading data from ./input.json
[*] visibility: (inputs: private, params: private, outputs: public)
[*] ------ scaled const node 2: 7 -> 14
[*] assigning configuration buckets to operations
[*] public inputs lengths: [1]
[*] loading params from "kzg.params"
[*] loading verification key from "proof.vk"
[*] visibility: (inputs: private, params: private, outputs: public)
[*] ------ scaled const node 2: 7 -> 14
[*] assigning configuration buckets to operations
[*] row cap: 3
[*] number of advices used: 5
[*] number of fixed used: 0
[*] number of instances used: 1
[*] configuring model
[*] output_shapes [[1]]
Warning: Yul is still experimental. Please use the output with care.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OddLength', /Users/myuser/.cargo/git/checkouts/snark-verifier-972b60abf3a1213b/df03d89/snark-verifier/src/loader/evm/util.rs:124:25
stack backtrace:
   0:        0x102a7fbc6 - std::backtrace_rs::backtrace::libunwind::trace::h4f0e9c01f163c4f1
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102a7fbc6 - std::backtrace_rs::backtrace::trace_unsynchronized::hb39a678382d45ac4
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102a7fbc6 - std::sys_common::backtrace::_print_fmt::hbd5777a2fb61dee1
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x102a7fbc6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1f89b1287f05728
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x102aa093a - core::fmt::write::hb9a1d6cab1bed673
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/fmt/mod.rs:1232:17
   5:        0x102a7853c - std::io::Write::write_fmt::h0949db1b5c61fce6
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/io/mod.rs:1684:15
   6:        0x102a7f9aa - std::sys_common::backtrace::_print::hb76c16138015f78e
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x102a7f9aa - std::sys_common::backtrace::print::h8e468349d7519f72
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x102a812d3 - std::panicking::default_hook::{{closure}}::h82b6603ca5d1b345
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:271:22
   9:        0x102a81028 - std::panicking::default_hook::h5830f012475db027
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:290:9
  10:        0x102a8190b - std::panicking::rust_panic_with_hook::hd67e8d898f426d5c
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:692:13
  11:        0x102a81824 - std::panicking::begin_panic_handler::{{closure}}::h6a63947e5e6a54b8
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:583:13
  12:        0x102a80009 - std::sys_common::backtrace::__rust_end_short_backtrace::h36012dee40fe1f28
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x102a814ed - rust_begin_unwind
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:579:5
  14:        0x102a9dfe3 - core::panicking::panic_fmt::h2cc1687c896e545c
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/panicking.rs:64:14
  15:        0x102a9e4e5 - core::result::unwrap_failed::h715c60f28b381d9b
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/result.rs:1750:5
  16:        0x102922fb1 - snark_verifier::loader::evm::util::compile_yul::hf7f90817fb06fcf2
  17:        0x101a3b46d - ezkl::pfsys::evm::single::gen_evm_verifier::h338e05b48632184e
  18:        0x1017bbb01 - ezkl::execute::run::{{closure}}::h8ddeebef33d33c88
  19:        0x1017c3886 - tokio::runtime::park::CachedParkThread::block_on::h560b680d7d1b776d
  20:        0x10192f570 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hfb6352390f149a45
  21:        0x101757d6a - ezkl::main::h3dfd80b7011631a5
  22:        0x101915c96 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha81372c28a0deba6
  23:        0x1018c17dc - std::rt::lang_start::{{closure}}::hc0596ad399d4c743
  24:        0x102a72280 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2f964c0cf434021c
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/ops/function.rs:287:13
  25:        0x102a72280 - std::panicking::try::do_call::h6ab21d4a277d6bdf
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:487:40
  26:        0x102a72280 - std::panicking::try::hfb01fd452e665622
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:451:19
  27:        0x102a72280 - std::panic::catch_unwind::h62c2de4aaf1cecf6
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panic.rs:140:14
  28:        0x102a72280 - std::rt::lang_start_internal::{{closure}}::h8215e427c091b029
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/rt.rs:148:48
  29:        0x102a72280 - std::panicking::try::do_call::h894c678608cb6b0f
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:487:40
  30:        0x102a72280 - std::panicking::try::hff882471419c3f31
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:451:19
  31:        0x102a72280 - std::panic::catch_unwind::hc57428bace4d90b6
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panic.rs:140:14
  32:        0x102a72280 - std::rt::lang_start_internal::h10b5dd8fa4967274
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/rt.rs:148:20
  33:        0x101757f0c - _main
```

**Comment by alexander-camuto** [comment]
Hey @JSeam2 thanks so much for flagging this and the detailed bug report. It seems like an incorrectly formatted hex string is being generated when compiling the "yul" code into deployment bytecode within the [snark-verifier](https://github.com/privacy-scaling-explorations/snark-verifier/blob/main/snark-verifier/src/loader/evm/util.rs) package. 

I'll see if I can investigate further with the team that maintains that package.

**Comment by alexander-camuto** [comment]
Hmmm I added the example you specified to the CI / integration test pipeline in #131 and it seems to be passing. There's a test in there which explicitly tests that `create-evm-verifier` generates solidity code that can be verified. 

I'm also unable to replicate locally. 

Could you checkout #131 and run it the exact pipeline you described above on the `.json and `.onnx` example files that have been added to `examples/onnx/2l_relu_fc` and see if the issue persists ?

**Comment by JSeam2** [comment]
Thanks for the prompt response!

I have checkout #131 and run the exact pipeline and the issue persists. I have deleted and rebuilt the project. The prover works fine but it fails on the `create-evm-verifier`. This is the traceback I got

```
ezkl --bits=16 -K=17 --public-inputs --public-outputs create-evm-verifier -D ./examples/onnx/2l_relu_fc/input.json -M ./examples/onnx/2l_relu_fc/network.onnx --vk-path ./examples/onnx/2l_relu_fc/proof.vk --params-path=kzg.params --sol-code-path ./examples/onnx/2l_relu_fc/verify.sol
[*] 
 |          ███████╗███████╗██╗  ██╗██╗
 |          ██╔════╝╚══███╔╝██║ ██╔╝██║
 |          █████╗    ███╔╝ █████╔╝ ██║
 |          ██╔══╝   ███╔╝  ██╔═██╗ ██║
 |          ███████╗███████╗██║  ██╗███████╗
 |          ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝
 |  
 |          -----------------------------------------------------------
 |          Easy Zero Knowledge for Neural Networks.
 |          -----------------------------------------------------------
 |          
[*] {"command":{"CreateEVMVerifier":{"data":"./examples/onnx/2l_relu_fc/input.json","model":"./examples/onnx/2l_relu_fc/network.onnx","params_path":"kzg.params","vk_path":"./examples/onnx/2l_relu_fc/proof.vk","deployment_code_path":null,"sol_code_path":"./examples/onnx/2l_relu_fc/verify.sol","pfsys":"KZG"}},"args":{"tolerance":0,"scale":7,"bits":16,"logrows":17,"public_inputs":true,"public_outputs":true,"public_params":false,"max_rotations":512}}
[*] loading data from ./examples/onnx/2l_relu_fc/input.json
[*] visibility: (inputs: public, params: private, outputs: public)
[*] ------ scaled const node 2: 7 -> 14
[*] assigning configuration buckets to operations
[*] public inputs lengths: [3, 1]
[*] loading params from "kzg.params"
[*] loading verification key from "./examples/onnx/2l_relu_fc/proof.vk"
[*] visibility: (inputs: public, params: private, outputs: public)
[*] ------ scaled const node 2: 7 -> 14
[*] assigning configuration buckets to operations
[*] row cap: 3
[*] number of advices used: 5
[*] number of fixed used: 0
[*] number of instances used: 2
[*] configuring model
[*] output_shapes [[1]]
Warning: Yul is still experimental. Please use the output with care.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OddLength', /Users/myuser/.cargo/git/checkouts/snark-verifier-972b60abf3a1213b/df03d89/snark-verifier/src/loader/evm/util.rs:124:25
stack backtrace:
   0:        0x10cb56c06 - std::backtrace_rs::backtrace::libunwind::trace::h4f0e9c01f163c4f1
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10cb56c06 - std::backtrace_rs::backtrace::trace_unsynchronized::hb39a678382d45ac4
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10cb56c06 - std::sys_common::backtrace::_print_fmt::hbd5777a2fb61dee1
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10cb56c06 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1f89b1287f05728
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10cb7797a - core::fmt::write::hb9a1d6cab1bed673
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/fmt/mod.rs:1232:17
   5:        0x10cb4f57c - std::io::Write::write_fmt::h0949db1b5c61fce6
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/io/mod.rs:1684:15
   6:        0x10cb569ea - std::sys_common::backtrace::_print::hb76c16138015f78e
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x10cb569ea - std::sys_common::backtrace::print::h8e468349d7519f72
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10cb58313 - std::panicking::default_hook::{{closure}}::h82b6603ca5d1b345
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:271:22
   9:        0x10cb58068 - std::panicking::default_hook::h5830f012475db027
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:290:9
  10:        0x10cb5894b - std::panicking::rust_panic_with_hook::hd67e8d898f426d5c
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:692:13
  11:        0x10cb58864 - std::panicking::begin_panic_handler::{{closure}}::h6a63947e5e6a54b8
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:583:13
  12:        0x10cb57049 - std::sys_common::backtrace::__rust_end_short_backtrace::h36012dee40fe1f28
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x10cb5852d - rust_begin_unwind
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:579:5
  14:        0x10cb75023 - core::panicking::panic_fmt::h2cc1687c896e545c
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/panicking.rs:64:14
  15:        0x10cb75525 - core::result::unwrap_failed::h715c60f28b381d9b
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/result.rs:1750:5
  16:        0x10c9f9ff1 - snark_verifier::loader::evm::util::compile_yul::hf7f90817fb06fcf2
  17:        0x10bb1262d - ezkl::pfsys::evm::single::gen_evm_verifier::h338e05b48632184e
  18:        0x10b892cc1 - ezkl::execute::run::{{closure}}::h8ddeebef33d33c88
  19:        0x10b89aa46 - tokio::runtime::park::CachedParkThread::block_on::h560b680d7d1b776d
  20:        0x10ba06730 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hfb6352390f149a45
  21:        0x10b82ef2a - ezkl::main::h3dfd80b7011631a5
  22:        0x10b9ece56 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha81372c28a0deba6
  23:        0x10b99899c - std::rt::lang_start::{{closure}}::hc0596ad399d4c743
  24:        0x10cb492c0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2f964c0cf434021c
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/core/src/ops/function.rs:287:13
  25:        0x10cb492c0 - std::panicking::try::do_call::h6ab21d4a277d6bdf
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:487:40
  26:        0x10cb492c0 - std::panicking::try::hfb01fd452e665622
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:451:19
  27:        0x10cb492c0 - std::panic::catch_unwind::h62c2de4aaf1cecf6
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panic.rs:140:14
  28:        0x10cb492c0 - std::rt::lang_start_internal::{{closure}}::h8215e427c091b029
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/rt.rs:148:48
  29:        0x10cb492c0 - std::panicking::try::do_call::h894c678608cb6b0f
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:487:40
  30:        0x10cb492c0 - std::panicking::try::hff882471419c3f31
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panicking.rs:451:19
  31:        0x10cb492c0 - std::panic::catch_unwind::hc57428bace4d90b6
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/panic.rs:140:14
  32:        0x10cb492c0 - std::rt::lang_start_internal::h10b5dd8fa4967274
                               at /rustc/c5c7d2b37780dac1092e75f12ab97dd56c30861d/library/std/src/rt.rs:148:20
  33:        0x10b82f0cc - _main
```

Some additional details about my machine, maybe this could be a factor
MacOS Mojave Version 10.14.8
2.2GHz Intel Core i7
rustc 1.69.0-nightly (c5c7d2b37 2023-02-24)
cargo 1.69.0-nightly (9d5b32f50 2023-02-22)

**Comment by alexander-camuto** [comment]
Hmmm this is nice and weird. Can you see if your local `Cargo.lock` differs from the repo's ? In particular `snark-verifier` should have the tag: `tag=v2023_02_02#df03d898b841f71cbc36c2fb9fa07b8196f9623e`.

**Comment by JSeam2** [comment]
Here's my `snark-verifier` settings in my `Cargo.lock`. The tag matches.
```
[[package]]
name = "snark-verifier"
version = "0.1.0"
source = "git+https://github.com/privacy-scaling-explorations/snark-verifier?tag=v2023_02_02#df03d898b841f71cbc36c2fb9fa07b8196f9623e"
dependencies = [
 "bytes",
 "ecc",
 "halo2_proofs",
 "halo2curves 0.3.1",
 "hex",
 "itertools",
 "lazy_static",
 "num-bigint",
 "num-integer",
 "num-traits",
 "poseidon",
 "primitive-types",
 "rand",
 "revm",
 "rlp",
 "sha3 0.10.6",
]
```

I get the same error if I remove `--public-inputs` and `--public-outputs` or both `prove` and `create-evm-verifier`.

**Comment by JSeam2** [comment]
I have set up a new VM on the cloud with Ubuntu and gotten an error with the same snark-verifier library. Might be a problem with the rust 


System Specifications
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
```

Rust Specifications
```
rustc 1.69.0-nightly (7281249a1 2023-02-27)
cargo 1.69.0-nightly (9d5b32f50 2023-02-22)
```

`snark-verifier` details in `Cargo.lock`
```
[[package]]
name = "snark-verifier"
version = "0.1.0"
source = "git+https://github.com/privacy-scaling-explorations/snark-verifier?tag=v2023_02_02#df03d898b841f71cbc36c2fb9fa07b8196f9623e"
dependencies = [
 "bytes",
 "ecc",
 "halo2_proofs",
 "halo2curves 0.3.1",
 "hex",
 "itertools",
 "lazy_static",
 "num-bigint",
 "num-integer",
 "num-traits",
 "poseidon",
 "primitive-types",
 "rand",
 "revm",
 "rlp",
 "sha3 0.10.6",
]

```

Trace
```
ezkl --bits=16 -K=17 create-evm-verifier -D ./examples/onnx/2l_relu_fc/input.json -M ./examples/onnx/2l_relu_fc/network.onnx --pfsys=kzg --deployment-code-path ./examples/onnx/2l_relu_fc/proof.code --vk-path ./examples/onnx/2l_relu_fc/proof.vk --params-path=kzg.params --sol-code-path ./examples/onnx/2l_relu_fc/verify.sol
[*] 
 |          ███████╗███████╗██╗  ██╗██╗
 |          ██╔════╝╚══███╔╝██║ ██╔╝██║
 |          █████╗    ███╔╝ █████╔╝ ██║
 |          ██╔══╝   ███╔╝  ██╔═██╗ ██║
 |          ███████╗███████╗██║  ██╗███████╗
 |          ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝
 |  
 |          -----------------------------------------------------------
 |          Easy Zero Knowledge Linear Algebra.
 |          -----------------------------------------------------------
 |          
[*] {"command":{"CreateEVMVerifier":{"data":"./examples/onnx/2l_relu_fc/input.json","model":"./examples/onnx/2l_relu_fc/network.onnx","params_path":"kzg.params","vk_path":"./examples/onnx/2l_relu_fc/proof.vk","deployment_code_path":"./examples/onnx/2l_relu_fc/proof.code","sol_code_path":"./examples/onnx/2l_relu_fc/verify.sol","pfsys":"KZG"}},"args":{"tolerance":0,"scale":7,"bits":16,"logrows":17,"public_inputs":false,"public_outputs":true,"public_params":false,"max_rotations":512}}
[*] loading data from ./examples/onnx/2l_relu_fc/input.json
[*] visibility: (inputs: private, params: private, outputs: public)
[*] ------ scaled const node 1: 7 -> 14
[*] assigning configuration buckets to operations
[*] public inputs lengths: [1]
[*] loading params from "kzg.params"
[*] loading verification key from "./examples/onnx/2l_relu_fc/proof.vk"
[*] visibility: (inputs: private, params: private, outputs: public)
[*] ------ scaled const node 2: 7 -> 14
[*] assigning configuration buckets to operations
[*] row cap: 3
[*] number of advices used: 5
[*] number of fixed used: 0
[*] number of instances used: 1
[*] configuring model
[*] output_shapes [[1]]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/git/checkouts/snark-verifier-972b60abf3a1213b/df03d89/snark-verifier/src/loader/evm/util.rs:116:10
stack backtrace:
   0:     0x558eac4ea97a - std::backtrace_rs::backtrace::libunwind::trace::hed88b98b82d4f2e9
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x558eac4ea97a - std::backtrace_rs::backtrace::trace_unsynchronized::ha265951554c18f80
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558eac4ea97a - std::sys_common::backtrace::_print_fmt::h905c58b80bf24d6a
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x558eac4ea97a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h42fd3bc77561f5c7
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x558eac513abe - core::fmt::write::hb1a89058387c66a8
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/fmt/mod.rs:1232:17
   5:     0x558eac4e62b5 - std::io::Write::write_fmt::h807c51614e4697cf
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/io/mod.rs:1684:15
   6:     0x558eac4ea745 - std::sys_common::backtrace::_print::h94c45e542d878e8b
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x558eac4ea745 - std::sys_common::backtrace::print::hf09a0b93d8d5d616
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x558eac4ebeff - std::panicking::default_hook::{{closure}}::h854554d33df993ef
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:271:22
   9:     0x558eac4ebc3b - std::panicking::default_hook::h47e0374d899bdb79
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:290:9
  10:     0x558eac4ec4a8 - std::panicking::rust_panic_with_hook::h73cfebaefb6d5c31
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:692:13
  11:     0x558eac4ec3a9 - std::panicking::begin_panic_handler::{{closure}}::h2e79312bef9db676
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:583:13
  12:     0x558eac4eade6 - std::sys_common::backtrace::__rust_end_short_backtrace::h7972a918610407b0
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x558eac4ec0b2 - rust_begin_unwind
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:579:5
  14:     0x558eab178573 - core::panicking::panic_fmt::h28cbdee921d72b75
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:64:14
  15:     0x558eab178a23 - core::result::unwrap_failed::h06888dc16524e883
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/result.rs:1750:5
  16:     0x558eac367ff8 - snark_verifier::loader::evm::util::compile_yul::h89b605b7c9834663
  17:     0x558eab4d8512 - ezkl::pfsys::evm::single::gen_evm_verifier::hbcf53988d129816a
  18:     0x558eab2bf8fa - ezkl::execute::run::{{closure}}::hd1fb71f9c2babb27
  19:     0x558eab2c76a9 - tokio::runtime::park::CachedParkThread::block_on::h7543fb74a9afda7c
  20:     0x558eab4235d0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h93b96d49e9f3db37
  21:     0x558eab25d87f - ezkl::main::h6e0d4d6b51666bff
  22:     0x558eab40b133 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c7de4c9ef648c9e
  23:     0x558eab3b5ee9 - std::rt::lang_start::{{closure}}::h6e00727f13c7becf
  24:     0x558eac4dffec - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h48c8729af8a6ff12
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/ops/function.rs:287:13
  25:     0x558eac4dffec - std::panicking::try::do_call::hdf2e1f6f4368fb31
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:487:40
  26:     0x558eac4dffec - std::panicking::try::hea724c1ade5962ff
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:451:19
  27:     0x558eac4dffec - std::panic::catch_unwind::hdcdd0a298ad03783
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panic.rs:140:14
  28:     0x558eac4dffec - std::rt::lang_start_internal::{{closure}}::h0c425502b0be57bc
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/rt.rs:148:48
  29:     0x558eac4dffec - std::panicking::try::do_call::h32beca25987d6b3b
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:487:40
  30:     0x558eac4dffec - std::panicking::try::hc9754f7fcae5a897
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:451:19
  31:     0x558eac4dffec - std::panic::catch_unwind::h08f67080eecd472d
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panic.rs:140:14
  32:     0x558eac4dffec - std::rt::lang_start_internal::h8e228cde7368d2a9
                               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/rt.rs:148:20
  33:     0x558eab25da35 - main
  34:     0x7fc798aa8d90 - <unknown>
  35:     0x7fc798aa8e40 - __libc_start_main
  36:     0x558eab178c05 - _start
  37:                0x0 - <unknown>
```

**Comment by alexander-camuto** [comment]
Thanks so much for the extra details. Will investigate :)

**Comment by alexander-camuto** [comment]
Hey @JSeam2 -- you don't have `solc` installed on the remote machine ! Hence the OS not found error. I'll make it more prominent in the Readme that this is a required install for EVM-verification. 

Could you try installing solc, re-running on the remote, and also updating solc locally ?

**Comment by JSeam2** [comment]
@alexander-camuto I have reinstalled solc on both MacOS and the Ubuntu instance. It is indeed the problem with `solc`. 
Added a PR #135 making clear that `solc` needs to be installed.
