### ISSUE TITLE
GPU prove error

### ISSUE THREAD

**Issue by fixerivan** [zkonduit/ezkl#882]
when I use GPU mode on prove I get error:

thread '<unnamed>' panicked at /home/ubuntu/.cargo/git/checkouts/halo2-6e3592afd20216b6/8b13a0d/halo2_proofs/src/icicle.rs:76:50:
called `Result::unwrap()` on an `Err` value: InvalidContext

full backtrace output attached 

[backtrace.txt](https://github.com/user-attachments/files/18030583/backtrace.txt)

**Comment by alexander-camuto** [comment]
this sounds like a cuda install issue ngl but will merge some updates to icicle in a bit and lets see if those resolve you pb

**Comment by 9401adarsh** [comment]
Hello there, has there been any fix patched for this issue? Facing the same issue. Have attached the backtrace snippet. 

```
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/layer.py:2285: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py:106: UserWarning: You are exporting the model in training mode with onnx opset version 11. Opset versions lower than opset 12 will not be able to export nodes such as Dropout and BatchNorm correctly.
  warnings.warn(
thread '<unnamed>' panicked at /home/ubuntu/.cargo/git/checkouts/halo2-6e3592afd20216b6/8b13a0d/halo2_proofs/src/icicle.rs:28:56:
called `Result::unwrap()` on an `Err` value: UnknownError
stack backtrace:
   0:     0x7ec43ae2739a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hca750ad87bb2f1d4
   1:     0x7ec43ab7916b - core::fmt::write::h133a0eb20f0a6a5d
   2:     0x7ec43adecde2 - std::io::Write::write_fmt::h0b1c7497ddea4e96
   3:     0x7ec43ae28a67 - std::panicking::default_hook::{{closure}}::h7dd45b5804215332
   4:     0x7ec43ae29d75 - std::panicking::rust_panic_with_hook::h4bf66cb658082ab2
   5:     0x7ec43ae29575 - std::panicking::begin_panic_handler::{{closure}}::h7a19fc32e0e387d7
   6:     0x7ec43ae294d9 - std::sys::backtrace::__rust_end_short_backtrace::h6117389318248cc0
   7:     0x7ec43ae294c4 - rust_begin_unwind
   8:     0x7ec43ab773b2 - core::panicking::panic_fmt::h1817a57f977b857c
   9:     0x7ec43ab7e7a5 - core::result::unwrap_failed::h99589da762c28d07
  10:     0x7ec43a5dbeaf - std::sys::sync::once::futex::Once::call::h3260b3e49207b486
  11:     0x7ec43a44c9bf - halo2_proofs::poly::kzg::commitment::ParamsKZG<E>::setup::h8af90b46981cec3a
  12:     0x7ec43aaf35ea - ezkl::bindings::python::__pyfunction_gen_srs::he3e6ce347661c54c
  13:     0x7ec43acc7c21 - pyo3::impl_::trampoline::trampoline::h44ebee2cca7d17b9
  14:     0x7ec43aaf3481 - ezkl::bindings::python::<impl ezkl::bindings::python::gen_srs::MakeDef>::_PYO3_DEF::trampoline::h7bc8c583aa727bf6
  15:     0x5864603527d2 - <unknown>
  16:     0x5864603490bb - _PyObject_MakeTpCall
  17:     0x586460342dfe - _PyEval_EvalFrameDefault
  18:     0x58646036eff0 - <unknown>
  19:     0x7ec45420928e - <unknown>
  20:     0x7ec4542090a4 - <unknown>
  21:     0x5864603490bb - _PyObject_MakeTpCall
  22:     0x58646049007a - <unknown>
  23:     0x58646034619f - <unknown>
  24:     0x586460343575 - _PyEval_EvalFrameDefault
  25:     0x58646035302c - _PyFunction_Vectorcall
  26:     0x58646033d5ff - _PyEval_EvalFrameDefault
  27:     0x58646035302c - _PyFunction_Vectorcall
  28:     0x58646033d5ff - _PyEval_EvalFrameDefault
  29:     0x58646035302c - _PyFunction_Vectorcall
  30:     0x58646033d5ff - _PyEval_EvalFrameDefault
  31:     0x58646035302c - _PyFunction_Vectorcall
  32:     0x58646033d5ff - _PyEval_EvalFrameDefault
  33:     0x58646035302c - _PyFunction_Vectorcall
  34:     0x58646034243a - _PyEval_EvalFrameDefault
  35:     0x586460360101 - <unknown>
  36:     0x58646033e6e0 - _PyEval_EvalFrameDefault
  37:     0x58646035302c - _PyFunction_Vectorcall
  38:     0x58646033d5ff - _PyEval_EvalFrameDefault
  39:     0x58646035302c - _PyFunction_Vectorcall
  40:     0x58646033d5ff - _PyEval_EvalFrameDefault
  41:     0x58646035302c - _PyFunction_Vectorcall
  42:     0x58646033f7df - _PyEval_EvalFrameDefault
  43:     0x58646035302c - _PyFunction_Vectorcall
  44:     0x58646033d5ff - _PyEval_EvalFrameDefault
  45:     0x58646035302c - _PyFunction_Vectorcall
  46:     0x58646033d5ff - _PyEval_EvalFrameDefault
  47:     0x586460360361 - <unknown>
  48:     0x586460474ffa - <unknown>
  49:     0x58646046a918 - <unknown>
  50:     0x7ec459551ac3 - <unknown>
  51:     0x7ec4595e2bf4 - clone
  52:                0x0 - <unknown>
Processing ONNX files for proof generation...
/workspace/artifacts/runs/phase4b-bounded-peft-20260423T034102Z

```

**Comment by peter941221** [comment]
I opened a fix for this here: #1028\n\nWhat I found locally on Linux / Python GPU builds was a two-part issue:\n\n1. Python gen_srs, setup, and prove were bypassing the shared device initialization path, so they could stay on CPU even when ICICLE_BACKEND_INSTALL_DIR was set.\n2. After forcing Python onto the CUDA path, backend loading still needed the ICICLE frontend shared libraries to be globally visible for later dlopen calls.\n\nI validated the patch locally on 2026-05-17 in WSL on an RTX 5090 with a minimal Python chain:\n\ngen_settings -> compile_circuit -> gen_witness -> setup -> prove\n\nBefore the patch, Python only logged Registering DEVICE: device=CPU. After the patch, it reaches Registering DEVICE: device=CUDA and setup / prove complete successfully.
